### ISSUE TITLE
mc:edit doesn't output on <mc-image>

### ISSUE THREAD

**Issue by tkatchenko** [homerjam/mjml-mailchimp#21]
When adding `mc:edit` to an `<mc-image>` element it doesn't include it in the output.

**Comment by Tomato997** [comment]
Yeah, experienced the same issue but fixed it by myself.
In /mjml-mailchimp/lib/mc-image.js just replace the file with the one attached, then it should work :)
Let me know if it worked :)
[mc-image.zip](https://github.com/homerjam/mjml-mailchimp/files/9133411/mc-image.zip)

**Comment by Tomato997** [comment]
@homerjam Can you fix that for all please? :)

**Comment by homerjam** [comment]
@Tomato997 please can you submit a PR?

**Comment by Tomato997** [comment]
Yeah sorry, did that now :) @homerjam
